### PR TITLE
Add the ability to create owning adapters

### LINKED ISSUE #2: Unable to create a owning adapter
Although types are described like `FmtToIo<W>`, it is only possible to create examples from special cases like `FmtToIo<&mut W>`. 

This can be fixed by changing the description of the `WriteExtension` trait to:
```rs
pub trait WriteExtension<T> {
    type Adapter;

    fn write_adapter(self) -> Self::Adapter;
}
```

And implementations can be fixed like (`io::Write` is implemented for `&mut W`):
```rs
impl<W: io::Write> WriteExtension<FmtToIo<W>> for W {
    type Adapter = FmtToIo<W>;

    fn write_adapter(self) -> FmtToIo<W> {
        FmtToIo {
            inner: self,
            error: None,
        }
    }
}
```

However such a solution would break the API, a softer option might be to add a `new()` function to the `FmtToIo` and `IoToHasher` structures, which would already take `T` at once instead of `&mut T`:
```rs
impl<W: io::Write> FmtToIo<W> {
    pub fn new(inner: W) -> Self {
        Self { inner, error: None }
    }
}
```

P.S. I would do a fork and a pull request if the formatting and compilation settings you use could be posted so I can run the tests successfully (all my settings are standard).

### PR DESCRIPTION
**Pull request by Hedgehogo**
The basic solution to [this issue](https://github.com/SUPERCILEX/io-adapters/issues/2#issue-2568685885).

Fixes #2

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
Nice, I like this. Get rid of the version change and run `UPDATE_EXPECT=1 cargo t` I believe.

**Comment by Hedgehogo** [comment]
I have a test crashing with this error, that's what I wrote about at the end of the original issue.
```
---- api stdout ----
thread 'api' panicked at C:\Users\Professional\.cargo\registry\src\index.crates.io-6f17d22bba15001f\supercilex-tests-0.4.5\src/lib.rs:84:14:
called `Result::unwrap()` on an `Err` value: SerdeJsonError(Error("missing field `const`", line: 1, column: 702))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SUPERCILEX** [comment]
Oh shoot, try updating the supercilex-tests dep to 0.4.8. Otherwise this will have to wait ~1 week till I get back.

**Comment by Hedgehogo** [comment]
Are you sure you don't want me to change the version of this crate? According to the eighth clause of the semver standard, the major version must be incremented when making changes that break backwards compatibility. Even though the library hasn't been released yet, it already has users.

**Comment by Hedgehogo** [comment]
> Oh shoot, try updating the supercilex-tests dep to 0.4.8.

Changing the version of `supercilex-tests` does not fix the problem.

**Comment by SUPERCILEX** [comment]
> > Oh shoot, try updating the supercilex-tests dep to 0.4.8.
> 
> Changing the version of `supercilex-tests` does not fix the problem.

Are you running a recent version of nightly? If yes, then my stuff is broken and I need to update the public-api dep in supercilex-tests and then update the dep in this lib.

---

Regarding the version change, like sure but I'll update the version in the commit that publishes it. If you mean people are depending on the master branch directly and not a specific commit hash instead of using cargo, that ain't my problem lol.

**Comment by Hedgehogo** [comment]
> Are you running a recent version of nightly? If yes, then my stuff is broken and I need to update the public-api dep in supercilex-tests and then update the dep in this lib.

I'm running version `2024-10-05`. When I try to upgrade to `2024-10-13` I have problems. But I think you meant not so new version anyway.

**Comment by SUPERCILEX** [comment]
Yeah, I'll have a computer in about a week so I'll fix it then.

**Pull request merged**
